### ISSUE TITLE
Issue installing due to TimeDependentSum

### ISSUE THREAD

**Issue by diogenes500** [HaeffnerLab/IonSim.jl#114]
I am having an issue installing IonSim. It may be that some dependencies are broken, namely TimeDependentSum from QuantumOptics. Below shows the relevant error. As of this date, is IonSim installing correctly?

[ Info: Precompiling IonSim [511e77fe-ab93-41f7-8f07-8f89809c6435]
ERROR: LoadError: UndefVarError: `TimeDependentSum` not defined
Stacktrace:
 [1] top-level scope
   @ C:\Users\xxx\.julia\packages\QuantumOptics\6utec\src\time_dependent_operators.jl:3
 [2] include(mod::Module, _path::String)
   @ Base .\Base.jl:457
 [3] include(x::String)
   @ QuantumOptics.timeevolution C:\Users\xxx\.julia\packages\QuantumOptics\6utec\src\QuantumOptics.jl:18
 [4] top-level scope
   @ C:\Users\xxx\.julia\packages\QuantumOptics\6utec\src\QuantumOptics.jl:22
 [5] include
   @ .\Base.jl:457 [inlined]
 [6] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt128}}, source::String)
   @ Base .\loading.jl:2049
 [7] top-level scope
   @ stdin:3
in expression starting at C:\Users\xxx\.julia\packages\QuantumOptics\6utec\src\time_dependent_operators.jl:3
in expression starting at C:\Users\xxx\.julia\packages\QuantumOptics\6utec\src\QuantumOptics.jl:1
in expression starting at stdin:3
ERROR: LoadError: Failed to precompile QuantumOptics [6e0679c1-51ea-5a7c-ac74-d61b76210b0c] to "C:\\Users\\xxx\\.julia\\compiled\\v1.9\\QuantumOptics\\jl_D608.tmp".

**Comment by abdulkaderatiya** [comment]
Hi,
please try to install older Quantum optics version and should work.

BR
Abdulkader

**Comment by neil-glikin** [comment]
IonSim was indeed not installing correctly due to a bad combination of specified dependency versions. This should be fixed now.
