### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by ajrazander** [HaeffnerLab/IonSim.jl#115]
Hi!

Curious to know if there will be a python equivalent of this package? Or even migration to python?

No offense to Julia ;), but many trapped ion experiments use python or are switching to python based control (i. e. ARTIQ). Would be great to have the tools in this package match control software for seamless integration. I’d be interested in contributing to such an effort

**Comment by dnadlinger** [comment]
Here in the @OxfordIonTrapGroup, we have a lot of Julia-based tooling for things like fast quantum state tomography with bootstrapping, generating transport waveforms, etc., which we seamlessly integrate into ARTIQ experiments (or Python scripts) using [`pyjulia`](https://github.com/JuliaPy/pyjulia) without any issues.

**Comment by ajrazander** [comment]
I appreciate the reference to pyjulia. I am still curious about a python implementation though.

**Comment by neil-glikin** [comment]
Hey folks, thanks for your interest. There are no plans for a python version of IonSim, but I could imagine supporting an effort to create such a thing if we find that there are enough people interested in contributing to it.
