### ISSUE TITLE
Allow the creation of heterogeneous chains of Ions

### ISSUE THREAD

**Issue by marwahaha** [HaeffnerLab/IonSim.jl#32]
this needs to happen after #25

**Comment by marwahaha** [comment]
joe requests this happens before 1.0

**Comment by neil-glikin** [comment]
A possibly useful reference: (likely one of many): Appendix A of master's thesis "Machine Learning and Optimization Techniques for Trapped-ion Quantum Simulators" by Yi Hong Teoh, University of Waterloo
https://uwspace.uwaterloo.ca/bitstream/handle/10012/17322/Teoh_Yi%20Hong.pdf?sequence=1
