### ISSUE TITLE
Compare the runtime of IonSim vs QuantumOptics

### ISSUE THREAD

**Issue by marwahaha** [HaeffnerLab/IonSim.jl#33]
It will be hard to define a reference. 
Compare against quantumoptics.jl

**Comment by jbroz11** [comment]
I think it would be worthwhile just to illustrate how simulation times scale with eg. 
* the size of the atomic Hilbert space
* the size of the vibrational Hilbert space
* the bandwidth of the RWA
for some simple dynamics, like a blue sideband Rabi transition and a COM Molmer-Sorensen interaction.

We could also consider comparing the simulation times using our constructed Hamiltonian versus constructing an analogous Hamiltonian completely within the preconstructed framework of QuantumOptics.jl. If there's a substantial improvement in efficiency for certain classes of dynamics, it would be worth highlighting that.
