### ISSUE TITLE
Style/Consistency Checks

### ISSUE THREAD

**Issue by neil-glikin** [HaeffnerLab/IonSim.jl#73]
The general hope here is to make sure that use of IonSim is easy and intuitive for a user, basically matching up with intuitive expectation as best as possible. This is a list of some of my thoughts of items to consider for this. Many of them are questions about how we should handle stuff.

Julian/coding style
- Is it bad form to have different methods defined in different files? (e.g. transitionfrequency, some in ions.jl and some in traps.jl)
- Consistency of argument variable names (I vs ion)
- Ordering of arguments (ion first/last, trap first/last?)
- Use of "set" in functions that end in !
- Function naming: eg stark_shift vs starkshift
- Using functions to modify structs vs directly accessing them
- Outputs for print/show
- When/how errors are thrown/what type of errors vs warnings in various situations
  - Start error messages with capital or lowercase letters?
- Defining a module: within the file or around the include statements for the file?
- Import or export statements first?
	
Specific to IonSim
- Is Efield_from_pi_time a good name
- Default value of "timescale" should be 1, not 1e-6
- How to make sure that making new ion species is "easy" based off of some template
- Names of things
  - In particular "trap"
- Enforcing m to be rational (where?)
- Should we do intensity instead of E field
- Some functions allow sublevels to be ID'd by an index (Int), but most don't. Should they? Which ones should?
- Functions that involve a transition accepting a tuple as argument vs two different arguments
- Use of ionposition vs position
- Setting of parameters when constructing stuff
  - Be able to set mode Fock state size when creating rather than having to reference and then `set mode.N =`
- Be able to set constant parameters in a nice way (e.g. `L.E` returns a number not a function)
- "stark shift" should be named something different so that it's not confusing
- Ability to construct from top down: set up an empty `Chamber` first, then fill it in

**Comment by marwahaha** [comment]
goal: making docstrings have consistent style

**Comment by neil-glikin** [comment]
Just updated first comment

**Comment by neil-glikin** [comment]
Resources

https://docs.julialang.org/en/v1/manual/style-guide/
https://github.com/invenia/BlueStyle

**Comment by marwahaha** [comment]
https://github.com/domluna/JuliaFormatter.jl (?)

**Comment by marwahaha** [comment]
from Kristian:
> It would be nice to create an empty Chamber(), then we consider the trapping potentials *for the ions* in IonTrap, then add the Laser and IonTrap into the Chamber.

**Comment by marwahaha** [comment]
Also: Is our convention for phrases:

    with underscores, like ion_configuration
    with capital letters, like IonConfiguration
    with no spacing, like ionconfiguration

**Comment by jbroz11** [comment]
I've been following `ion_configuration` for file names. `IonConfiguration` for structs and `ionconfiguration` for function names. Sometimes I break the last rule if it is not readable.
