### ISSUE TITLE
Document the things that IonSim does not do

### ISSUE THREAD

**Issue by neil-glikin** [HaeffnerLab/IonSim.jl#76]
(At least right now)

- Electronic transitions whose multipole order is not E1 or E2 (most importantly, does not do M1 transitions)
- Linear strings with shaped potential
- Magnetic field gradient fluctuations
- Multi-valence-electron states
  - e.g. Ytterbium with its D3[3/2]1/2 state
- Natively handle incoherent dynamics due to spontaneous emission
- Multispecies ion chains
- Micromotion

**Comment by marwahaha** [comment]
I think the best thing to do is add this list to https://docs.ionsim.org/ .

**Comment by neil-glikin** [comment]
- Coupling of normal modes to each other (eg due to trap frequency modulation, Kerr coupling)
