### ISSUE TITLE
typo in examples

### ISSUE THREAD

**Issue by marwahaha** [HaeffnerLab/IonSim.jl#92]
![image](https://user-images.githubusercontent.com/2541209/178662559-4634389e-f54c-4571-851d-1ff39b510057.png)

I doubt this is correct. $\sum_{i=1,2}$ but then $\sigma^{(1)} + \sigma^{(2)}$??

**Comment by neil-glikin** [comment]
It looks like $i$ is enumerating lasers here. Which is confusing because in the second bullet point it's enumerating the ion. I think this should stick with the convention at the beginning of $m$ indexing lasers and $n$ indexing ions.

**Comment by jbroz11** [comment]
Neil's right. I tend to recycle indices in new expressions. Feel free to change it if you'd like.
