### ISSUE TITLE
[IJulia issue] Fix IJulia rendering problem

### ISSUE THREAD

**Issue by marwahaha** [HaeffnerLab/IonSim.jl#99]
If you use the ``proper'' form of docstrings; i.e. indent, space, then docstring, the output is correct for IJulia, but then broken in Jupyter.

Joe reported this. He said he would file a IJulia issue (probably a bug on their side).

The purpose of this issue is to track the IJulia bug (when it is reported).

**Comment by jbroz11** [comment]
seems to be solved now
